time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset01.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset01.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset02.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset02.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset03.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset03.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset04.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset04.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset05.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset05.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset06.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset06.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset07.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset07.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset08.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset08.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset09.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset09.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset10.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset10.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset11.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset11.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset12.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset12.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset13.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset13.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset14.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset14.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset15.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset15.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset16.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset16.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset17.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset17.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset18.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset18.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset19.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset19.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset20.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset20.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset21.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset21.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset22.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset22.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset23.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset23.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset24.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset24.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset25.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset25.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset26.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset26.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset27.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset27.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset28.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset28.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset29.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset29.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset30.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset30.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset31.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset31.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset32.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset32.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset33.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset33.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset34.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset34.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset35.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset35.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset36.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset36.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset37.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset37.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset38.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset38.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset39.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset39.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset40.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset40.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset41.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset41.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset42.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset42.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset43.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset43.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset44.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset44.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset45.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset45.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset46.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset46.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset47.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset47.txt | wc -l
time algorithms/automaton-on-suffix-tree/STzad11/bin/Release/net8.0/STzad11 datasets/dataset48.txt | wc -l
time algorithms/improved-naive/regex-dot/bin/Release/net8.0/regex-dot datasets/dataset48.txt | wc -l
